export const GET_PRODUCTS = 'GET_PRODUCTS'

export const GET_TOTAL_AMOUNT_CART = 'GET_TOTAL_AMOUNT_CART'
export const GET_PRODUCTS_CART = 'GET_PRODUCTS_CART'
export const INSERT_PRODUCT_CART = 'INSERT_PRODUCT_CART'
export const UPDATE_CART = 'UPDATE_CART'

export const TOGGLE_BAG = 'TOGGLE_BAG'